name: Hello World!

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
        
      - name: Print current date in UTC
        run: date -u
        
      - name: List files in long format
        run: ls -l
